# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
