# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170627_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_photos/thumbnails'),
        ),
    ]
